name: Build Docker Image with jsonrpc-to-firestark

on:
  workflow_dispatch:
    inputs:
      firestarkVersion:
        description: "firestark version"
        required: true
      jsonrpcToFirestarkVersion:
        description: "jsonrpc-to-firestark version"
        required: true

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-latest"

    env:
      DOCKER_REPOSITORY: "starknet/firestark"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Login to Docker Hub"
        uses: "docker/login-action@v1.6.0"
        with:
          username: "${{ secrets.DOCKER_HUB_USERNAME }}"
          password: "${{ secrets.DOCKER_HUB_PASSWORD }}"

      - name: "Build Docker image"
        run: |
          docker build -t ${DOCKER_REPOSITORY}:${{ github.event.inputs.firestarkVersion }}-jsonrpc-${{ github.event.inputs.jsonrpcToFirestarkVersion }} --build-arg FIRESTARK_VERSION=${{ github.event.inputs.firestarkVersion }} --build-arg JSONRPC_TO_FIRESTARK_VERSION=${{ github.event.inputs.jsonrpcToFirestarkVersion }} -f ./Dockerfile.jsonrpc .

      - name: "Push Docker image"
        run: |
          docker push ${DOCKER_REPOSITORY}:${{ github.event.inputs.firestarkVersion }}-jsonrpc-${{ github.event.inputs.jsonrpcToFirestarkVersion }}
