name: Lint

on:
  push:
    branches:
      - "master"

  pull_request:
    branches:
      - "master"

jobs:
  formatter:
    strategy:
      fail-fast: true

    name: Check with formatters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-go@v3
        with:
          go-version: "1.18.3"
          check-latest: true

      - name: Install prettier
        run: |
          yarn global add prettier

      - name: Install buf
        run: |
          go install github.com/bufbuild/buf/cmd/buf@v1.6.0

      - name: Install shfmt
        run: |
          go install mvdan.cc/sh/v3/cmd/shfmt@v3.5.1

      - name: Check format with prettier
        run: |
          prettier --check '**/*.{md,yaml,yml}'

      - name: Check go format
        run: |
          test -z "$(gofmt -l .)"

      - name: Check proto format
        run: |
          test -z "$(buf format -d)"

      - name: Check shell script format
        run: |
          test -z "$(shfmt -d -i 2 .)"
