[package]
name = "stark_hash"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "stark_hash"
path = "src/lib.rs"

[build-dependencies]
stark_curve = { path = "../stark_curve" }

[dependencies]
# paritys scale codec locks us here
bitvec = "0.20.4"
fake = { version = "2.5.0", features = ["derive"] }
rand = { version = "0.8.5" }
rand_core = "0.6.4"
serde = { workspace = true }
stark_curve = { path = "../stark_curve" }

[dev-dependencies]
assert_matches = { workspace = true }
criterion = { workspace = true }
hex = "0.4.3"
pretty_assertions = "1.3.0"
serde_json = { workspace = true }

[[bench]]
name = "stark_hash"
harness = false
