[package]
name = "stark_hash_python"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "starknet_pathfinder_crypto"
crate-type = ["cdylib"]

[dependencies]
num-bigint = "0.4.3"
pyo3 = { version = "0.17.1", features = ["extension-module", "num-bigint"] }
stark_curve = { path = "../stark_curve" }
stark_hash = { path = "../stark_hash" }
stark_poseidon = { path = "../stark_poseidon" }
