[workspace]
members = [
    "crates/common",
    "crates/ethereum",
    "crates/gateway-client",
    "crates/gateway-test-fixtures",
    "crates/gateway-types",
    "crates/merkle-tree",
    "crates/p2p",
    "crates/p2p_bootstrap",
    "crates/p2p_proto",
    "crates/p2p_proto_derive",
    "crates/pathfinder",
    "crates/retry",
    "crates/rpc",
    "crates/serde",
    "crates/stark_curve",
    "crates/stark_hash",
    "crates/stark_poseidon",
    "crates/storage",
]
exclude = [
    "crates/load-test",
    "crates/stark_hash_python",
]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.66"
assert_matches = "1.5.0"
clap =  "4.1.13"
const_format = "0.2.31"
criterion = "0.5.1"
fake = { version = "2.5.0", features = ["derive"] }
rand = "0.8.5"
semver = "1.0.14"
serde = "1.0.160"
serde_json = "1.0.96"
serde_with = "2.1.0"
thiserror = "1.0.37"
tokio = "1.24.2"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
